LOAD DATA
INFILE 'data.txt'
INSERT INTO TABLE employees
WHEN NAME = 'SCOTT'
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
(
    NAME CHAR, 
    JOB CHAR, 
    SAL INTEGER EXTERNAL, 
    DEPTNO INTEGER EXTERNAL
)
